# Generated by Django 4.0.4 on 2022-05-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_receipt_finalreceipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=250)),
                ('role', models.CharField(choices=[('MG', 'Manager'), ('RC', 'Receptionist')], max_length=2)),
            ],
        ),
    ]
